# mkdocs.yml
site_name: Clustered Federated Learning (CFL)

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [.\FedCL]  # actually not needed, default

nav: 
  - index.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - examples.md